config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :surveys 
    resources :attempts
    resources :companies
    resources :answers
    resources :pages

    get '/verify', :to => 'pages#verify'
    get '/privacy', :to => 'pages#privacy'
    get '/register', :to => 'pages#register'
    get '/help', :to => 'pages#help'
    get '/about', :to => 'pages#about'

    authenticated :user do 
      root 'surveys#index', as: "authenticated_root"
    end 

     root to: "pages#index"

     delete 'attempts/:survey_id/:current_user' => 'attempts#delete_user_attempts', as: :delete_user_attempts

end

app/views/shared/_flash.html.erb
  <div class="flash">
    <% flash.each do |name, msg| %>
      <div class="alert alert-<%= correct_flash_name(name) %>" role="alert">
        <%= msg %>
      </div>
    <% end %>
  </div>

app/views/shared/_footer.html.erb
<footer class="footer">
	<ul class="footer-text">
		 <li class="text-muted">Copyright © 2015  <%= link_to 'GoPlex', 'http://www.goplex.co', target: '_blank' %></li>
 		<li><%= link_to "Privacy Policy", privacy_path %></li>
 		<li><%= link_to ' About GoPlex', 'http://www.goplex.co/about', target: '_blank' %></li>
 	</ul>
</footer>

app/views/shared/_gem_header_info.html.erb
    	<div class="nav navbar-default" >
           <div class="container">
          <ul class="nav navbar-nav">
         
            <li>
              <%= link_to surveys_path do %>
                All surveys
                <span class='badge'> <%= surveys_count %> </span>
              <% end -%>
            </li>
            <% if current_admin %>
            <li>
              <%= link_to companies_path do %>
                All Companies
                <span class='badge'> <%= companies_count %> </span>
              <% end -%>
            </li>
            <% end %>

          <% if current_admin %>
              <li class="dropdown" id="special-drop">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Create Actions<span class="caret"></span></a>
                <ul class="dropdown-menu">
                   <li> <%= link_to ' New Opinion Poll', new_survey_path(type: 'poll') %> </li>
                    <li> <%= link_to ' New Quiz', new_survey_path(type: 'quiz') %> </li>
                    <li> <%= link_to ' New Score Survey', new_survey_path(type: 'score') %> </li>
                    <li> <%= link_to ' New Company', new_company_path %> </li>
                </ul>
          <% end %>

          </ul>
        </div>
    </div>

app/views/shared/_navbar.html.erb
<header>
  <div class="navbar navbar-default navbar-static-top" role="navigation">
    <div class="container">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <div class="navbar-header">
        <%= link_to (image_tag "goplex.png"), root_path, class: "nav navbar-left" %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
         <ul class="nav navbar-nav navbar-right">
            <li>
              <p class="navbar-text">
                 <li><%= link_to "How it works", :anchor => "anchor-point", id: "js-anchor" %></li>
                 <li><%= link_to "Register your company", "#" %></li>
                 <li><%= link_to "About", "#" %></li>
                 <li><%= link_to "Help", "#" %></li>
                <% if user_signed_in?%>
                  Logged in as:
                  <b> <%= current_user.email %> </b>
                  <%= link_to 'Log out', destroy_user_session_path, :method => :delete %>
                <% elsif admin_signed_in? %>
                   Logged in as:
                   <b><%= current_admin.email %> </b>
                   <%= link_to 'Log out', destroy_admin_session_path, :method => :delete %>
              </p> 
              <% else %>
            </li>
            <li><%= link_to "Sign in", new_user_session_path, id: "btn-custom-log" %></li>
               <% end %>
          </ul>
      </div>
    </div>
  </div>
  <% if current_user || current_admin %>
    <%= render 'shared/gem_header_info' %>
  <% end %>
</header>