config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :surveys 
    resources :attempts
    resources :companies
    resources :answers
    resources :pages

    get '/verify', :to => 'pages#verify'
    get '/privacy', :to => 'pages#privacy'
    get '/register', :to => 'pages#register'
    get '/help', :to => 'pages#help'
    get '/about', :to => 'pages#about'

    authenticated :user do 
      root 'surveys#index', as: "authenticated_root"
    end 

     root to: "pages#index"

     delete 'attempts/:survey_id/:current_user' => 'attempts#delete_user_attempts', as: :delete_user_attempts

end

app/models/company.rb
class Company < ActiveRecord::Base
	 attr_readonly :company_key
	 validates :name, presence: true, uniqueness: true
	 validates :company_key, presence: true, uniqueness: true
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
	before_filter :authenticate_admin!
	before_action :find_company, only: [:edit, :update, :show, :destroy]

	def index
		@company = Company.all
	end

	def show
	end


	def new
		@company = Company.new
	end

	def create
		@company = Company.new(company_params)

		if @company.save
			redirect_to @company
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @company.update(company_params)
			redirect_to @company
		else
			render 'edit'
		end 
	end

	def destroy
		@survey = Survey::Survey.all
		@survey_name = @survey.where(company_key: @company.company_key).name
		if @survey.where(company_key: @company.company_key).exists?
			flash[:notice] = "You cannot delete this company. It belongs to current active surveys"
			redirect_to companies_path
		else
			@company.destroy
			redirect_to companies_path
		end
	end  


	private




	def find_company
		@company = Company.find(params[:id])
	end 

	def company_params
		params.require(:company).permit(:name, :company_key)
	end 



end

app/controllers/company_controller.rb
class CompanyController < ApplicationController
end

app/helpers/company_helper.rb
module CompanyHelper
	
	def company
		@company = Company.all
	end 

	 def companies_count
	    if current_admin 
	      Company.count
	    end 
  	end

  	def survey_comp_active 
  		

  	end 

end

app/views/companies/_form.html.erb
<%= form_for @company do |f| %>
<%= f.label :name %>
<%= f.text_field :name, class: 'form-control' %>
<br>
<%= f.label	:company_key %>
<%= f.text_field :company_key, class: 'form-control', id: "key", :readonly => true %>

<% if current_page?(action: 'new') %>
<button type="button" id="mybutton" class='form-control'>Generate Key</button>
<% end %>
<br>
<%= f.submit class: 'pull-left btn btn-primary' %>

<% end %>

app/views/companies/edit.html.erb
<div class="container">
	<h4>Edit Company Details</h4>
	
	<%= render 'form' %>




</div>

app/views/companies/index.html.erb
<div class="container">
	
	<h4>Listing of Active Companies</h4>
	<h5><%= link_to "Create a new one", new_company_path %></h5>

	<table class="table">
		<th>Company Name</th>
		<th>Company Key</th>
		<th>Creation Date</th>
		<th>Edit</th>
		<th>Delete</th>

	<% @company.each do |company| %>
	<tr>
		<td><%= link_to company.name, company %></td>
		<td><%= company.company_key %></td>
		<td><%= company.created_at.strftime("%m/%d/%Y") %></td>
		<td><%= link_to edit_company_path(company), class: 'btn btn-default btn-sm' do %>
        <i class="fa fa-pencil-square-o"> Edit</i>
      <% end %></td>
		<td><%= link_to company_path(company), class: 'btn btn-default btn-sm', method: :delete, data: {confirm: "Are you sure you want to delete this company?"} do %>
        <i class="fa fa-trash-o"> Delete</i>
      <% end %></td>
	</tr>

	<% end %>
		</table>
</div>

app/views/companies/new.html.erb
<div class="container">
	<div class="col-md-6">


	<h4>Create a new Company</h4>
	
	<%= render 'form' %>



</div>
</div>

app/views/companies/show.html.erb
<div class="container">
	<h4>Company Details Page</h4>

	<tr>
		<td><h5><%= @company.name %></h5></td>
		<td><h5><%= @company.company_key %></h5></td>
	</tr>


	<%= link_to "Edit Company", edit_company_path %>
	<%= link_to "All Companies", companies_path %> 
	
	


</div>