config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :surveys 
    resources :attempts
    resources :companies
    resources :answers
    resources :pages

    get '/verify', :to => 'pages#verify'
    get '/privacy', :to => 'pages#privacy'
    get '/register', :to => 'pages#register'
    get '/help', :to => 'pages#help'
    get '/about', :to => 'pages#about'

    authenticated :user do 
      root 'surveys#index', as: "authenticated_root"
    end 

     root to: "pages#index"

     delete 'attempts/:survey_id/:current_user' => 'attempts#delete_user_attempts', as: :delete_user_attempts

end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController

before_filter :authenticate_any!
before_filter :load_survey, only: [:show, :edit, :update, :destroy]
 

  def index
    type = view_context.get_survey_type(params[:type])
    query = if type then Survey::Survey.where(survey_type: type) else Survey::Survey end

    if admin_signed_in?
        @surveys = query.order(created_at: :desc).page(params[:page]).per(15)
      elsif user_signed_in?
        @surveys = query.order(created_at: :desc).page(params[:page]).per(15).where(company_key: current_user.company_key)
    end 
  end

  def new
    @survey = Survey::Survey.new(survey_type: view_context.get_survey_type(params[:type]))
  end

  def create
    @survey = Survey::Survey.new(params_whitelist)

    if @survey.company_key.present?
      if @survey.valid? && @survey.save
        default_redirect
      else
        build_flash(@survey)
        render :new
      end
    else
      flash[:notice] = "You need a company"
      render 'new'
    end
  end

  def edit
  end

  def show
  end 



  def update
    if @survey.update_attributes(params_whitelist)
      default_redirect
    else
      build_flash(@survey)
      render :edit
    end
  end

  def destroy
    @survey.destroy
    default_redirect
  end

  private

  def authenticate_any!
    if admin_signed_in?
      true
    else
      authenticate_user!
    end 
  end 

  def default_redirect
    redirect_to surveys_path, notice: I18n.t("surveys_controller.#{action_name}")
  end

  def load_survey
    @survey = Survey::Survey.find(params[:id])
  end

  def params_whitelist
    params.require(:survey_survey).permit(Survey::Survey::AccessibleAttributes << :survey_type, :company_key)
  end
end

app/helpers/surveys_helper.rb
module SurveysHelper
  def link_to_remove_field(name, f)
    f.hidden_field(:_destroy) +
    __link_to_function(raw(name), "removeField(this)", :id =>"remove-attach", class: 'btn btn-default')
  end

  def new_survey
    new_survey_path
  end

  def edit_survey(resource)
    edit_survey_path(resource)
  end

  def survey_scope(resource)
    if action_name =~ /new|create/
      surveys_path(resource)
    elsif action_name =~ /edit|update/
      survey_path(resource)
    end
  end

  def attempt_scope(resource)
    if action_name =~ /new|create/
     attempts_path(resource)
    elsif action_name =~ /edit|update/
      attempt_path(resource)
    end
  end

  def link_to_add_field(name, f, association)
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object,:child_index => "new_#{association}") do |builder|
      render(association.to_s.singularize + "_fields", :f => builder)
    end
    __link_to_function(name, "addField(this, \"#{association}\", \"#{escape_javascript(fields)}\")",
    :id=>"add-attach",
    :class=>"btn btn-default")
  end

  def get_answer_fields attempt
    attempt.survey.questions.map { |q| Survey::Answer.new(question_id: q.id) }
  end

  def the_chosen_one? answer, option
    if answer.option_id == option.id then 'chosen' else nil end
  end

  def number_of_people_who_also_answered option_id
    count = number_of_people_who_also_answered_count(option_id)
    "<span class='number'> #{count} </span> #{'answer'.pluralize}".html_safe
  end

  def get_color_of_option answer, option
    if is_quiz?(answer.question.survey.survey_type)
      if option.correct
        'bg-success'
      elsif the_chosen_one?(answer, option)
        'bg-danger'
      end
    elsif is_score?(answer.question.survey.survey_type)
      get_weight_html_class option
    end
  end

  def get_survey_type survey_type
    get_survey_types[survey_type] || get_survey_types.invert[survey_type]
  end

  def get_survey_types
    { 0 => 'quiz',
      1 => 'score',
      2 => 'poll' }
  end

  def is_quiz? something
    something == 0 || something == 'quiz'
  end

  def is_score? something
    something == 1 || something == 'score'
  end

  def is_poll? something
    something == 2 || something == 'poll'
  end

  def get_weight option
    return unless is_score?(option.question.survey.survey_type)
    option.weight > 0 ? "(+#{option.weight})" : "(#{option.weight})"
  end

  def get_weight_html_class option
    return 'bg-warning' if option.weight == 0
    option.weight > 0 ? 'bg-success' : 'bg-danger'
  end

  def surveys_count type = get_survey_types.keys
    if current_admin 
      Survey::Survey.where(survey_type: type).count
    elsif current_user
      Survey::Survey.where(company_key: current_user.company_key).count
    end 
  end

  def number_of_questions survey
    survey.questions.count
  end

  def number_of_attempts survey
    survey.attempts.count
  end

  private

  def __link_to_function(name, on_click_event, opts={})
    link_to(name, 'javascript:;', opts.merge(onclick: on_click_event))
  end

  def has_weights? survey
    survey.questions.map(&:options).flatten.any? { |o| o.weight != 0 }
  end

end

app/views/surveys/_form.html.erb
<%= form_for(@survey, url: survey_scope(@survey), html: { class: 'survey-form clearfix' }, validate: true) do |f| %>
  <%= f.hidden_field :survey_type, value: @survey.survey_type %>
  <div class='field'>
    <div class='row'>
      <div class='form-group col-sm-4'>
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      <div class='form-group col-sm-4'>
        <%= f.label :attempts_number, 'Maximum number of attempts (0 is infinite)' %>
        <%= f.number_field :attempts_number, min: 0, class: 'form-control' %>
      </div>
      <div class='form-group col-sm-4'>
        <%= f.label :active %>
        <%= f.select :active, ['true', 'false'], {}, class: 'form-control' %>
      </div>
       <div class='form-group col-sm-4'>
        <%= f.label :company_key %>
        <%= f.collection_select :company_key, company.order(:name),:company_key,:name, include_blank: true %>
      </div>
    </div>
    <div class='row'>
      <div class='form-group col-sm-12'>
        <%= f.label :description %>
        <%= f.text_area :description, size: '100x5', class: 'form-control', style: 'max-width: 100%;' %>
      </div>
    </div>
    
    <div class='appendable'>
      <% if is_score?(@survey.survey_type) %>
        <br/>
        <div> In this type of survey, you have to enter a score for each question option (negative values are allowed) </div>
      <% end -%>
      <%= f.fields_for :questions do |builder| %>
        <%= render 'question_fields', f: builder %>
      <% end %>
    </div>
    <br/>
    <%= link_to_add_field 'Add a new Question', f, :questions %>
  </div>
  <%= f.submit 'Submit', class: 'pull-right btn btn-primary' %>
  <% end -%>
</div>

<script type='text/javascript'>
  // remove attachment field
  function removeField(link) {
    $(link).prev("input[type=hidden]").val("true");
    tag = $(link).closest(".field")
    tag.hide('slow');
  }

  // add attachment field
  function addField(link, association, content) {
    var new_id = new Date().getTime();
    var regexp = new RegExp("new_" + association, "g");
    var html = $(content.replace(regexp, new_id)).hide();
    var target = $(link).closest("div.field").find(".appendable").first();

    var last_height = 0
    html.appendTo(target).slideDown({
      duration: 'slow',
      progress: function () {
        delta = $(this).outerHeight(true) - last_height
        $(window).scrollTop( $(window).scrollTop() + delta );
        last_height = $(this).outerHeight(true);
      },
      complete: function () {
        $(this).find('input[type=text]').focus();
      }});
    }
</script>

app/views/surveys/_input_quiz.html.erb
<div class="checkbox col-xs-3 col-sm-2">
  <%= f.label :correct do %>
    <%= f.check_box :correct %>
    Correct answer
  <% end %>
</div>

app/views/surveys/_input_score.html.erb
<div class='form-group col-xs-3 col-sm-2'>
  <%= f.label :weight, class: 'sr-only' %>
  <%= f.number_field :weight, placeholder: 'weight', class: 'form-control' %>
</div>

app/views/surveys/_option_fields.html.erb
<div class="field">
  <div class="row">
    <div class="form-group col-xs-4">
      <%= f.label :text, class: 'sr-only' %>
      <%= f.text_field :text, placeholder: 'answer', class: 'form-control' %>
    </div>
    <%= render "input_#{get_survey_type(@survey.survey_type)}", f: f %>
    <div class="col-xs-4">
      <%= link_to_remove_field "Remove", f %>
    </div>
  </div>
</div>

app/views/surveys/_question_fields.html.erb
<div class='field clearfix'>
  <hr/>
  <h4>Question</h4>
  <div class='row'>
    <div class='form-group col-sm-4'>
      <%= f.label :text, class: 'sr-only' %>
      <%= f.text_field :text, placeholder: 'question', class: 'form-control' %>
    </div>
  </div>
  <ol class='appendable'>
    <%= f.fields_for :options do |builder| %>
      <%= render 'option_fields', :f => builder %>
    <% end -%>
  </ol>
  <%= link_to_add_field 'Add option', f, :options %>
  <%= link_to_remove_field 'Remove question', f %>
</div>

app/views/surveys/_survey.html.erb
<tr class="survey">
  <td class="table-center"> <%= render 'survey_label', survey_type: survey.survey_type %> </td>
  <td> <%= link_to survey.name, new_attempt_path(survey_id: survey.id), class: 'survey-name' %> </td>
  <td> <span class="survey-description"> <%= "#{survey.description}" %> </span> </td>
  <td class="table-center"> <%= number_of_questions(survey) %> </td>
  <% if current_admin %> 
  <td class="table-center"> <%= number_of_attempts(survey) %> </td>

  <td class="table-center survey-buttons">
    <div class="btn-group" role="group">
      <%= link_to edit_survey_path(survey.id), class: 'btn btn-default btn-sm' do %>
        <i class="fa fa-pencil-square-o"> Edit</i>
      <% end %>
      <%= link_to survey_path(survey.id), class: 'btn btn-default btn-sm', method: :delete, data: {confirm: "Are you sure you want to delete this survey?"} do %>
        <i class="fa fa-trash-o"> Delete</i>
      <% end %>
    </div>
  </td>
<% end %>
</tr>

app/views/surveys/_survey_label.html.erb
<% string_type ||= get_survey_type(survey_type) %>
<% with_badges ||= nil %>
<% if !with_badges || (with_badges && surveys_count(survey_type) > 0) %>
  <%= link_to surveys_path(type: string_type), class: "label label-survey label-survey-#{string_type} #{'label-with-badges' if with_badges}" do %>
    <span><%= string_type.capitalize %></span>
    <% if with_badges %>
      <span class='badge label-badge label-badge-<%= string_type %>'><%= surveys_count(survey_type) %></span>
    <% end %>
  <% end %>
<% end %>

app/views/surveys/_survey_label_all.html.erb
<%= link_to surveys_path, class: "label label-survey label-survey-all label-with-badges" do %>
  <span> All </span>
  <span class='badge label-badge label-badge-all'> <%= surveys_count %> </span>
<% end %>

app/views/surveys/edit.html.erb
<div class="container">
  <h2>
    Edit Survey
    <small> <%= render 'survey_label', survey_type: @survey.survey_type %> </small>
  </h2>
  <%= render 'form' %>
</div>

app/views/surveys/index.html.erb
<div class="container">
  <div class="questionnaires_<%= action_name %>">
    <h2>
      My Dashboard
    </h2>
    <hr>
    <% if @surveys.empty? %>
      <p> There are no surveys </p>
    <% else %>
      <p>
        <% if current_admin %>
        Filter by type:
        <%= render 'survey_label_all' %>
        <%= render partial: 'survey_label', collection: get_survey_types.keys, as: :survey_type, locals: { with_badges: true } %>
      </p>
      <% end %>
      <table class='table table-nonfluid survey-table'>
        <thead>
          <tr>
            <th></th>
            <th>Name</th>
            <th>Description</th>
            <th>Questions</th>
            <% if current_admin %>
            <th>Participants</th>
            <% end %>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <%= render partial: 'survey', collection: @surveys %>
        </tbody>
      </table>
      <%= paginate @surveys %>
    <% end %>
  </div>
</div>

app/views/surveys/new.html.erb
<div class="container">
  <h2>
    New Survey
    <small> <%= render 'survey_label', survey_type: @survey.survey_type %> </small>
  </h2>
  <hr/>
  <%= render 'form' %>
</div>